service1:
    build: .
    volumes:
        - .:/app
    links:
        - service2
    expose:
        - 80
    environment:
        TOLERANCE_SERVICE_NAME: "First Service"

service2:
    build: .
    volumes:
        - .:/app
    expose:
        - 80
    environment:
        TOLERANCE_SERVICE_NAME: "Second Service"
