services:
    app.neo4j.client_builder:
        class:   Neoxygen\NeoClient\ClientBuilder
        factory: [Neoxygen\NeoClient\ClientBuilder, create]
        calls:
            -
                - addConnection
                -
                    - 'default'
                    - 'http'
                    - %neo4j_host%
                    - %neo4j_port%
                    - true
                    - %neo4j_username%
                    - %neo4j_password%

    app.neo4j.client:
        class: Neoxygen\NeoClient\Client
        factory: ["@app.neo4j.client_builder", build]
